### ISSUE TITLE
Deployment Error - Unable to Deploy Stack

### ISSUE THREAD

**Issue by inkwell84** [filebot/filebot-docker#19]
Getting the above error from Portainer when trying to deploy filebot node via the stack editor. 

```
version: '3.3'
services:
  filebot-node:
    container_name: filebotnode
    image: rednoah/filebot:node
    restart: unless-stopped
    volumes:
      - /abcdefg/docker/filebotnode:/data
      - /abcdefg/media:/volume1
    ports:
      - 5452:5452
```
